import { StyleSheet } from 'react-native'

export const COLORS = {
  ink: '#14213D',
  muted: '#758198',
  blue: '#3155D9',
  blueDark: '#213DAA',
  pale: '#F3F6FC',
  line: '#E5EAF3',
  white: '#FFFFFF',
  red: '#B42318',
  redPale: '#FFF0EE',
}

export const styles = StyleSheet.create({
  // Shared layout helpers and loading states.
  flex: { flex: 1 },
  // Sign-in screen.
  signInSafe: { flex: 1, backgroundColor: '#1B315E' },
  safeArea: { flex: 1, backgroundColor: COLORS.pale },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.pale },
  loadingLabel: { marginTop: 14, color: COLORS.muted, fontSize: 14 },
  signInScroll: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 22, paddingTop: 24, paddingBottom: 28, backgroundColor: '#1B315E' },
  signInTop: { marginBottom: 26, alignItems: 'center' },
  loginLogo: { color: COLORS.white, fontSize: 48, fontWeight: '900', letterSpacing: -2, marginTop: 18 },
  loginLogoAccent: { color: '#60A5FA' },
  loginPortal: { color: '#9AAED0', fontSize: 12, letterSpacing: 2.2, marginTop: 4 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 32 },
  brandMark: { width: 42, height: 42, borderRadius: 14, backgroundColor: COLORS.blue, alignItems: 'center', justifyContent: 'center' },
  brandMarkSmall: { width: 34, height: 34, borderRadius: 11 },
  brandMarkText: { color: COLORS.white, fontSize: 23, fontWeight: '800' },
  brandMarkTextSmall: { fontSize: 19 },
  brandName: { color: COLORS.ink, fontSize: 21, fontWeight: '800', letterSpacing: -0.5 },
  brandNameSmall: { fontSize: 18 },
  signInCard: { backgroundColor: '#FFFFFF12', borderRadius: 24, padding: 22, borderWidth: 1, borderColor: '#FFFFFF30', shadowColor: '#071225', shadowOpacity: 0.15, shadowRadius: 20, shadowOffset: { width: 0, height: 9 }, elevation: 2 },
  cardTitle: { color: COLORS.white, fontSize: 22, fontWeight: '800' },
  cardSubtitle: { color: '#A9BAD7', fontSize: 13, marginTop: 5, marginBottom: 23 },
  inputLabel: { color: '#DCE6F7', fontSize: 13, fontWeight: '700', marginBottom: 8 },
  passwordLabel: { marginTop: 17 },
  input: { height: 54, borderRadius: 13, borderWidth: 1, borderColor: '#FFFFFF38', backgroundColor: '#FFFFFF14', paddingHorizontal: 14, color: COLORS.white, fontSize: 15 },
  signInPasswordRow: { height: 54, flexDirection: 'row', alignItems: 'center', borderRadius: 13, borderWidth: 1, borderColor: '#FFFFFF38', backgroundColor: '#FFFFFF14' },
  signInPasswordInput: { flex: 1, height: 52, paddingHorizontal: 14, color: COLORS.white, fontSize: 15 },
  passwordEyeButton: { width: 48, height: 52, alignItems: 'center', justifyContent: 'center' },
  passwordEyeText: { color: '#DCE6F7', fontSize: 19, fontWeight: '700' },
  // Shared buttons, alerts, and class cards.
  primaryButton: { height: 54, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.blue, marginTop: 22 },
  primaryButtonText: { color: COLORS.white, fontSize: 15, fontWeight: '800' },
  disabledButton: { opacity: 0.65 },
  pressedButton: { backgroundColor: COLORS.blueDark },
  facultyOnly: { marginTop: 15, textAlign: 'center', color: '#A9BAD7', fontSize: 11, lineHeight: 16 },
  footerText: { marginTop: 25, marginBottom: 8, textAlign: 'center', color: '#929CAF', fontSize: 11 },
  errorBanner: { padding: 12, backgroundColor: COLORS.redPale, borderColor: '#F9D1CC', borderWidth: 1, borderRadius: 12, marginTop: 16 },
  errorText: { color: COLORS.red, fontSize: 13, lineHeight: 18 },
  classCard: { flexDirection: 'row', alignItems: 'stretch', borderRadius: 17, backgroundColor: COLORS.white, marginBottom: 10, borderWidth: 1, borderColor: COLORS.line, overflow: 'hidden' },
  classAccent: { width: 4, backgroundColor: COLORS.blue },
  classAccentTeal: { backgroundColor: '#23A58F' },
  classMain: { flex: 1, paddingVertical: 14, paddingLeft: 13, paddingRight: 8 },
  classTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  classCode: { color: COLORS.blue, fontSize: 10, fontWeight: '800', letterSpacing: 0.6 },
  classDay: { color: COLORS.muted, fontSize: 10, fontWeight: '700' },
  className: { color: COLORS.ink, fontSize: 14, lineHeight: 19, fontWeight: '700', marginTop: 5 },
  classMetaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 7 },
  classMeta: { color: COLORS.muted, fontSize: 10 },
  metaDot: { color: '#AAB3C1', marginHorizontal: 6 },
  classTime: { minWidth: 78, paddingVertical: 14, paddingHorizontal: 10, alignItems: 'flex-end', justifyContent: 'center' },
  classStart: { color: COLORS.ink, fontSize: 12, fontWeight: '800' },
  classEnd: { color: COLORS.muted, fontSize: 10, marginTop: 4 },
  emptyTitle: { color: COLORS.ink, fontSize: 13, fontWeight: '800', textAlign: 'center' },
  emptyCopy: { color: COLORS.muted, fontSize: 11, marginTop: 5, lineHeight: 16, textAlign: 'center' },
  retryPanel: { flex: 1, justifyContent: 'center', padding: 24 },
  setupLoadingScreen: { flex: 1, backgroundColor: '#F3F6FC', justifyContent: 'center', padding: 22 },
  setupLoadingCard: { alignItems: 'center', backgroundColor: COLORS.white, borderRadius: 22, paddingHorizontal: 24, paddingVertical: 32, borderWidth: 1, borderColor: '#E4EAF2', shadowColor: '#1B315E', shadowOpacity: 0.08, shadowRadius: 18, shadowOffset: { width: 0, height: 7 }, elevation: 2 },
  setupLoadingTitle: { color: '#1B315E', fontSize: 22, fontWeight: '900', marginTop: 20 },
  setupLoadingCopy: { color: '#52627A', fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 8 },
  setupLoadingHint: { color: '#91A0B5', fontSize: 11, marginTop: 8 },
  title: { color: COLORS.ink, fontSize: 23, fontWeight: '800', marginTop: 12 },
  bodyCopy: { color: COLORS.muted, fontSize: 14, lineHeight: 21, marginTop: 8 },
  textButtonLabel: { color: COLORS.blue, fontSize: 14, fontWeight: '700' },
  // Faculty dashboard header, tabs, subjects, and notifications.
  homeRoot: { flex: 1, backgroundColor: '#F7F9FC' },
  homeHeader: { backgroundColor: '#1B315E', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 18 },
  homeDate: { color: COLORS.white, fontSize: 14, fontWeight: '800', marginBottom: 23 },
  greetingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  greetingCopy: { flex: 1, paddingRight: 12 },
  homeGreeting: { color: COLORS.white, fontSize: 22, fontWeight: '800', letterSpacing: -0.5 },
  homeSubtitle: { color: '#A9BAD7', fontSize: 12, marginTop: 4 },
  headerAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: COLORS.blue, borderWidth: 3, borderColor: '#5E8FFF', alignItems: 'center', justifyContent: 'center' },
  headerAvatarText: { color: COLORS.white, fontSize: 15, fontWeight: '800' },
  headerAvatarImage: { width: 44, height: 44, borderRadius: 22 },
  headerStats: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#FFFFFF24', borderRadius: 14, paddingVertical: 12, paddingHorizontal: 14, marginTop: 16 },
  headerStat: { flex: 1 },
  headerStatLabel: { color: '#C0CDE3', fontSize: 10 },
  headerStatValue: { color: COLORS.white, fontSize: 20, fontWeight: '800', marginTop: 2 },
  homeError: { paddingHorizontal: 16, backgroundColor: '#F7F9FC' },
  homeScroll: { flex: 1 },
  homeScrollContent: { paddingHorizontal: 15, paddingTop: 16, paddingBottom: 24 },
  welcomeCard: { backgroundColor: '#172747', borderRadius: 20, padding: 18, marginBottom: 13, shadowColor: '#172747', shadowOpacity: 0.14, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 3 },
  welcomeOverline: { color: '#8295B9', fontSize: 11, fontWeight: '800', letterSpacing: 1.2 },
  welcomeName: { color: COLORS.white, fontSize: 19, fontWeight: '800', marginTop: 6 },
  welcomeMeta: { color: '#A8B8D4', fontSize: 12, marginTop: 3 },
  scheduleWelcomeNote: { color: '#D2DCF0', backgroundColor: '#FFFFFF12', borderLeftWidth: 3, borderLeftColor: '#60A5FA', borderRadius: 9, padding: 10, marginTop: 11, fontSize: 11, fontStyle: 'italic' },
  quoteText: { color: '#D2DCF0', backgroundColor: '#FFFFFF12', borderLeftWidth: 3, borderLeftColor: '#60A5FA', borderRadius: 10, padding: 12, marginTop: 13, fontSize: 13, fontStyle: 'italic' },
  dayTabs: { marginHorizontal: -15, marginBottom: 12, maxHeight: 44 },
  dayTabsContent: { paddingHorizontal: 15, gap: 7, alignItems: 'center' },
  dayTab: { paddingHorizontal: 15, paddingVertical: 10, borderRadius: 22, borderWidth: 1, borderColor: '#E0E7F1', backgroundColor: COLORS.white },
  dayTabActive: { backgroundColor: COLORS.blue, borderColor: COLORS.blue },
  dayTabText: { color: '#8291AA', fontSize: 12, fontWeight: '700' },
  dayTabTextActive: { color: COLORS.white },
  schedulePanel: { backgroundColor: COLORS.white, borderRadius: 19, padding: 16, borderWidth: 1, borderColor: '#E4EAF2', shadowColor: '#223451', shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 1 },
  schedulePanelHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 13 },
  scheduleDayTitle: { color: COLORS.ink, fontSize: 17, fontWeight: '800' },
  scheduleCount: { color: COLORS.muted, fontSize: 11, fontWeight: '600' },
  dayEmpty: { alignItems: 'center', paddingVertical: 25 },
  dailyClassRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 7, borderBottomWidth: 1, borderColor: '#EDF1F6' },
  dailyClassTime: { width: 78, color: '#8291AA', fontSize: 12, lineHeight: 17, fontWeight: '800' },
  dailyClassCard: { flex: 1, borderLeftWidth: 4, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 9 },
  dailyClassCode: { fontSize: 15, lineHeight: 19, fontWeight: '900' },
  dailyClassName: { fontSize: 12, lineHeight: 16, fontWeight: '400', marginTop: 3 },
  dailyClassMeta: { fontSize: 11, lineHeight: 14, marginTop: 2, fontWeight: '400', opacity: 0.78 },
  roomSectionTitle: { color: COLORS.ink, fontSize: 13, fontWeight: '800', marginTop: 18, marginBottom: 9 },
  roomStatusCard: { backgroundColor: '#1B315E', borderRadius: 15, padding: 14, marginBottom: 4 },
  roomStatusTop: { flexDirection: 'row', alignItems: 'center' },
  roomStatusOverline: { color: '#90A5C8', fontSize: 9, fontWeight: '800', letterSpacing: 0.8 },
  roomStatusRoom: { color: COLORS.white, fontSize: 18, fontWeight: '900', marginTop: 4 },
  roomStatusCourse: { color: '#E2EAF7', fontSize: 10, fontWeight: '700', marginTop: 3 },
  roomStatusMeta: { color: '#A9BAD7', fontSize: 9, marginTop: 3 },
  roomTimeBox: { alignItems: 'flex-end', marginLeft: 8 },
  roomTimeValue: { color: '#FF7378', fontSize: 20, fontWeight: '900' },
  roomTimeLabel: { color: '#A9BAD7', fontSize: 8 },
  roomProgressTrack: { height: 5, borderRadius: 4, backgroundColor: '#FFFFFF30', overflow: 'hidden', marginTop: 12 },
  roomProgressFill: { height: 5, borderRadius: 4, backgroundColor: '#3DDF75' },
  roomStatusBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
  roomStatusFaculty: { color: '#CFD9EA', fontSize: 9 },
  roomStatusBadge: { color: '#BFD0EA', fontSize: 9, fontWeight: '800' },
  roomStatusBadgeActive: { color: '#75E99A' },
  roomEmpty: { backgroundColor: COLORS.white, padding: 14, borderRadius: 13, borderWidth: 1, borderColor: COLORS.line },
  roomEmptyText: { color: COLORS.muted, fontSize: 10, lineHeight: 15 },
  scheduleDetailSheet: { maxHeight: '88%', backgroundColor: COLORS.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 14, paddingTop: 13, paddingBottom: 22 },
  scheduleDetailHero: { backgroundColor: '#1B315E', borderRadius: 13, padding: 14, marginBottom: 14 },
  scheduleDetailCode: { color: '#A9BAD7', fontSize: 10, fontWeight: '800', letterSpacing: 0.4 },
  scheduleDetailTitle: { color: COLORS.white, fontSize: 16, lineHeight: 21, fontWeight: '900', marginTop: 5 },
  scheduleDetailDepartment: { color: '#A9BAD7', fontSize: 10, marginTop: 4 },
  scheduleDetailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 9 },
  scheduleDetailTile: { width: '47%', minHeight: 61, backgroundColor: '#F4F6FA', borderRadius: 11, paddingHorizontal: 11, paddingVertical: 9, marginBottom: 9 },
  scheduleDetailWideTile: { width: '100%' },
  detailTileLabel: { color: '#8A9AB3', fontSize: 8, fontWeight: '800', letterSpacing: 0.6 },
  detailTileValue: { color: COLORS.ink, fontSize: 12, lineHeight: 16, fontWeight: '700', marginTop: 4 },
  scheduleDetailFaculty: { backgroundColor: '#F4F6FA', borderRadius: 11, paddingHorizontal: 11, paddingVertical: 10, marginBottom: 10 },
  scheduleDetailClose: { height: 42, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0F3F7', marginTop: 7 },
  scheduleDetailCloseText: { color: '#52627A', fontSize: 12, fontWeight: '700' },
  summaryButton: { backgroundColor: COLORS.white, borderRadius: 14, borderColor: '#E4EAF2', borderWidth: 1, padding: 15, marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  summaryButtonText: { color: COLORS.blue, fontSize: 14, fontWeight: '800' },
  summaryChevron: { color: COLORS.blue, fontSize: 22 },
  bottomNav: { height: 64, flexDirection: 'row', backgroundColor: COLORS.white, borderTopWidth: 1, borderColor: '#E4EAF2', paddingBottom: 3 },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', position: 'relative', gap: 2 },
  navIcon: { color: '#93A1B6', fontSize: 17, fontWeight: '700' },
  navLabel: { color: '#93A1B6', fontSize: 10, fontWeight: '700' },
  navActive: { color: COLORS.blue },
  navIndicator: { position: 'absolute', top: 0, width: '70%', height: 3, borderBottomLeftRadius: 3, borderBottomRightRadius: 3, backgroundColor: COLORS.blue },
  subjectsPanel: { backgroundColor: COLORS.white, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#E4EAF2' },
  panelTitle: { color: COLORS.ink, fontSize: 18, fontWeight: '800' },
  panelSubtitle: { color: '#8A9AB3', fontSize: 12, marginTop: 4, marginBottom: 15 },
  subjectTableHead: { flexDirection: 'row', paddingVertical: 10, borderBottomWidth: 2, borderColor: '#E0E7F1' },
  subjectHeadText: { color: '#91A0B6', fontSize: 9, fontWeight: '800' },
  subjectRow: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingVertical: 13, borderBottomWidth: 1, borderColor: '#E8EDF4' },
  subjectCode: { color: '#52627B', fontSize: 12, fontWeight: '800' },
  subjectName: { color: COLORS.ink, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  subjectRoom: { color: '#9AA7BA', fontSize: 10, marginTop: 3 },
  subjectSection: { color: '#56657D', fontSize: 11, textAlign: 'right' },
  notificationRow: { flexDirection: 'row', gap: 11, paddingVertical: 14, borderBottomWidth: 1, borderColor: '#EDF1F6' },
  notificationDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: COLORS.blue, marginTop: 5 },
  notificationCopy: { flex: 1 },
  notificationTitle: { color: '#465875', fontSize: 13, fontWeight: '800' },
  notificationText: { color: '#60718D', fontSize: 12, lineHeight: 18, marginTop: 3 },
  notificationTime: { color: '#9AA9BF', fontSize: 10, marginTop: 5 },
  // Profile, settings, and schedule-summary sheets.
  modalShade: { ...StyleSheet.absoluteFill, zIndex: 30, backgroundColor: '#07122599', justifyContent: 'flex-end' },
  modalBackdrop: { ...StyleSheet.absoluteFill },
  profileSheet: { backgroundColor: '#1D2A40', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 18, paddingTop: 13, paddingBottom: 28 },
  sheetHandle: { width: 38, height: 5, borderRadius: 4, backgroundColor: '#C8D2E1', alignSelf: 'center', marginBottom: 25 },
  profileIdentity: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  profileAvatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: COLORS.blue, alignItems: 'center', justifyContent: 'center' },
  profileAvatarImage: { width: 58, height: 58, borderRadius: 29 },
  profileName: { color: COLORS.white, fontSize: 16, fontWeight: '800' },
  profileRole: { color: '#A9B8CE', fontSize: 12, marginTop: 3 },
  sheetDivider: { height: 1, backgroundColor: '#344158', marginBottom: 10 },
  profileAction: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10 },
  profileActionText: { color: COLORS.white, fontSize: 14, fontWeight: '700' },
  profileArrow: { color: '#8291A8', fontSize: 22 },
  signOutAction: { color: '#FF6B70', fontSize: 14, fontWeight: '700' },
  summarySheet: { backgroundColor: COLORS.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingTop: 14, paddingBottom: 28 },
  summaryStats: { flexDirection: 'row', gap: 8, marginTop: 8 },
  summaryStat: { flex: 1, padding: 12, borderRadius: 13, backgroundColor: '#F2F5FA' },
  summaryStatValue: { color: COLORS.blue, fontSize: 17, fontWeight: '800' },
  summaryStatLabel: { color: '#7E8DA4', fontSize: 10, marginTop: 4 },
  summaryDetail: { color: '#64748B', fontSize: 13, lineHeight: 19, marginTop: 16 },
  summaryClose: { backgroundColor: COLORS.blue, borderRadius: 13, alignItems: 'center', paddingVertical: 14, marginTop: 19 },
  summaryCloseText: { color: COLORS.white, fontSize: 14, fontWeight: '800' },
  settingsTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  closeSettings: { color: COLORS.blue, fontWeight: '800', fontSize: 13 },
  settingLine: { paddingVertical: 13, borderBottomWidth: 1, borderColor: '#E9EEF5' },
  settingLabel: { color: '#8A9AB3', fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  settingValue: { color: COLORS.ink, fontSize: 14, marginTop: 5 },
  // PBT-inspired weekly timetable and Day/Night selector.
  scheduleIntro: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  scheduleIntroTitle: { color: COLORS.ink, fontSize: 17, fontWeight: '800' },
  scheduleIntroSubtitle: { color: COLORS.muted, fontSize: 11, marginTop: 4 },
  summaryButtonCompact: { backgroundColor: COLORS.blue, borderRadius: 10, paddingHorizontal: 13, paddingVertical: 9 },
  shiftSwitch: { alignSelf: 'flex-start', flexDirection: 'row', padding: 3, borderRadius: 11, backgroundColor: '#E9EEF6', marginBottom: 12 },
  shiftButton: { paddingHorizontal: 18, paddingVertical: 8, borderRadius: 9 },
  shiftButtonActive: { backgroundColor: COLORS.blue },
  shiftButtonText: { color: '#687991', fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  shiftButtonTextActive: { color: COLORS.white },
  gridZoomControls: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-end', gap: 8, marginTop: -5, marginBottom: 9 },
  gridZoomButton: { minWidth: 31, height: 30, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line },
  gridZoomButtonText: { color: COLORS.blue, fontSize: 15, fontWeight: '800' },
  gridZoomValue: { color: COLORS.muted, fontSize: 10, minWidth: 36, textAlign: 'center' },
  pbtGridCard: { backgroundColor: COLORS.white, borderRadius: 15, borderWidth: 1, borderColor: COLORS.line, overflow: 'hidden', paddingBottom: 4 },
  pbtGridHeader: { height: 42, flexDirection: 'row', backgroundColor: '#F0F3F8', borderBottomWidth: 1, borderColor: COLORS.line },
  pbtTimeHeader: { width: 66, justifyContent: 'center', alignItems: 'center' },
  pbtDayHeader: { width: 112, justifyContent: 'center', alignItems: 'center', borderLeftWidth: 1, borderColor: COLORS.line },
  pbtHeaderText: { color: '#5F6E83', fontSize: 10, fontWeight: '800' },
  pbtGridBody: { flexDirection: 'row' },
  pbtTimeColumn: { width: 66, backgroundColor: '#F8FAFC' },
  pbtTimeSlot: { justifyContent: 'flex-start', alignItems: 'flex-end', paddingRight: 4, borderBottomWidth: 1, borderColor: '#E5EAF1' },
  pbtTimeText: { color: '#74839A', fontSize: 9, marginTop: -6 },
  pbtDayColumn: { width: 112, borderLeftWidth: 1, borderColor: COLORS.line, position: 'relative' },
  pbtGridSlot: { borderBottomWidth: 1, borderColor: '#E9EDF3' },
  pbtClassBlock: { position: 'absolute', left: 3, right: 3, backgroundColor: '#10A66A', borderColor: '#07824E', borderWidth: 1, borderRadius: 6, padding: 4, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  pbtClassCode: { color: COLORS.white, fontSize: 10, fontWeight: '900', textAlign: 'center' },
  pbtClassSection: { color: COLORS.white, fontSize: 9, fontWeight: '700', textAlign: 'center', marginTop: 2 },
  pbtClassRoom: { color: '#EDFFF6', fontSize: 8, textAlign: 'center', marginTop: 2 },
  pbtClassName: { color: '#EDFFF6', fontSize: 8, textAlign: 'center', marginTop: 2 },
  pbtEmpty: { color: COLORS.muted, textAlign: 'center', fontSize: 11, padding: 12 },
  scheduleReadOnly: { color: '#92A0B3', fontSize: 10, textAlign: 'center', marginTop: 9 },
  // PBT course list and load breakdown inside the summary sheet.
  courseSummarySheet: { maxHeight: '88%', backgroundColor: COLORS.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 16, paddingTop: 14, paddingBottom: 25 },
  summaryTableHeader: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 2, borderColor: COLORS.line, gap: 5 },
  summaryColumnTitle: { color: '#8796AB', fontSize: 8, fontWeight: '900' },
  summaryCourseRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 11, gap: 5, borderBottomWidth: 1, borderColor: '#E9EEF5' },
  summaryCourseCode: { color: '#43546C', fontSize: 10, fontWeight: '900' },
  summaryCourseName: { color: COLORS.ink, fontSize: 10, lineHeight: 14, fontWeight: '600' },
  summaryCourseUnits: { color: '#8C9AB0', fontSize: 9, marginTop: 2 },
  summaryCourseSection: { color: '#52627B', fontSize: 9 },
  summaryEmpty: { textAlign: 'center', color: COLORS.muted, padding: 18, fontSize: 12 },
  summaryLoadBox: { backgroundColor: '#F7F9FC', borderRadius: 12, paddingHorizontal: 11, paddingVertical: 7, marginTop: 13 },
  summaryLine: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, paddingVertical: 6 },
  summaryLineLabel: { flex: 1, color: '#485971', fontSize: 10, fontWeight: '700' },
  summaryLineValue: { color: COLORS.ink, fontSize: 10, textAlign: 'right' },
  summaryLoadDivider: { height: 1, backgroundColor: '#E0E7EF', marginVertical: 5 },
  // Full-screen editable settings view and form controls.
  settingsOverlay: { ...StyleSheet.absoluteFill, zIndex: 40, backgroundColor: '#F7F9FC' },
  settingsHeader: { height: 60, backgroundColor: '#1B315E', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15 },
  settingsBack: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#FFFFFF20', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  settingsBackText: { color: COLORS.white, fontSize: 27, lineHeight: 30, marginTop: -3 },
  settingsHeaderTitle: { color: COLORS.white, fontSize: 16, fontWeight: '800' },
  settingsTabs: { maxHeight: 53, backgroundColor: '#F7F9FC' },
  settingsTabsContent: { paddingHorizontal: 13, paddingVertical: 10, gap: 7 },
  settingsTab: { borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: COLORS.white, borderWidth: 1, borderColor: '#E1E7F0' },
  settingsTabActive: { backgroundColor: COLORS.blue, borderColor: COLORS.blue },
  settingsTabText: { color: '#8796AB', fontSize: 10, fontWeight: '700' },
  settingsTabTextActive: { color: COLORS.white },
  settingsScroll: { flex: 1 },
  settingsContent: { padding: 13, paddingBottom: 28 },
  settingsCard: { backgroundColor: COLORS.white, borderRadius: 15, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: '#E9EEF4', shadowColor: '#172747', shadowOpacity: 0.04, shadowRadius: 7, shadowOffset: { width: 0, height: 3 }, elevation: 1 },
  settingsCardTitle: { color: COLORS.ink, fontSize: 14, fontWeight: '800' },
  settingsCardSubtitle: { color: '#91A0B5', fontSize: 10, marginTop: 3, marginBottom: 12 },
  settingsAvatarRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 3 },
  settingsAvatar: { width: 62, height: 62, borderRadius: 31, backgroundColor: COLORS.blue, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: '#DCE7F9' },
  settingsAvatarImage: { width: 56, height: 56, borderRadius: 28 },
  settingsAvatarText: { color: COLORS.white, fontSize: 19, fontWeight: '900' },
  settingsPhotoActions: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  settingsPhotoButton: { backgroundColor: COLORS.blue, borderRadius: 9, paddingHorizontal: 12, paddingVertical: 10 },
  settingsPhotoButtonText: { color: COLORS.white, fontSize: 10, fontWeight: '800' },
  settingsPhotoRemove: { backgroundColor: '#F0F3F7', borderRadius: 9, paddingHorizontal: 12, paddingVertical: 10 },
  settingsPhotoRemoveText: { color: '#52627A', fontSize: 10, fontWeight: '700' },
  settingsInfoText: { color: '#8291A8', fontSize: 11, lineHeight: 16 },
  formColumns: { flexDirection: 'row', gap: 9 },
  settingsField: { flex: 1, marginBottom: 11 },
  settingsFieldLabel: { color: '#52627A', fontSize: 9, fontWeight: '800', letterSpacing: 0.3, marginBottom: 5, textTransform: 'uppercase' },
  settingsInput: { minHeight: 42, borderRadius: 10, borderWidth: 1, borderColor: '#DDE5EF', backgroundColor: COLORS.white, paddingHorizontal: 11, paddingVertical: 8, color: COLORS.ink, fontSize: 12 },
  settingsSecureRow: { minHeight: 42, flexDirection: 'row', alignItems: 'center', borderRadius: 10, borderWidth: 1, borderColor: '#DDE5EF', backgroundColor: COLORS.white },
  settingsSecureInput: { flex: 1, minHeight: 40, paddingHorizontal: 11, paddingVertical: 8, color: COLORS.ink, fontSize: 12 },
  settingsEyeButton: { width: 42, minHeight: 40, alignItems: 'center', justifyContent: 'center' },
  settingsEyeText: { color: '#71819A', fontSize: 17, fontWeight: '700' },
  settingsMultiline: { minHeight: 74, textAlignVertical: 'top' },
  settingsReadOnly: { backgroundColor: '#F0F3F7', color: '#7E8DA4' },
  choiceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  choiceChip: { borderRadius: 9, borderWidth: 1, borderColor: '#DDE5EF', paddingHorizontal: 10, paddingVertical: 8, backgroundColor: COLORS.white },
  choiceChipActive: { borderColor: COLORS.blue, backgroundColor: '#EBF1FF' },
  choiceChipText: { color: '#71819A', fontSize: 10, fontWeight: '600' },
  choiceChipTextActive: { color: COLORS.blue, fontWeight: '800' },
  currentChoice: { color: '#8796AB', fontSize: 9, marginTop: 5 },
  notificationSetting: { minHeight: 57, flexDirection: 'row', alignItems: 'center', backgroundColor: '#F6F8FB', borderRadius: 11, paddingHorizontal: 10, marginBottom: 7 },
  notificationSettingTitle: { color: COLORS.ink, fontSize: 11, fontWeight: '700' },
  notificationSettingDescription: { color: '#98A6BA', fontSize: 9, marginTop: 3 },
  settingsSaveButton: { minHeight: 43, borderRadius: 10, backgroundColor: COLORS.blue, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  settingsSaveText: { color: COLORS.white, fontSize: 12, fontWeight: '800' },
  settingsFeedback: { color: '#52627A', fontSize: 11, textAlign: 'center', padding: 10 },
})
